name: QuicPair
options:
  bundleIdPrefix: com.hamada
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  QuicPair:
    type: application
    platform: iOS
    sources:
      - path: QuicPair
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hamada.QuicPair.yuki
        PRODUCT_NAME: QuicPair
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: T47FJ2TW22
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: QuicPair/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
